{% set version = "3.6.1" %}

# Recipe for a static libarchive with support for the features needed for
# conda-package-handling (bzip2, zlib, zstd).
# This is not a general purpose libarchive

package:
  name: _libarchive_static_for_cph
  version: {{ version }}

source:
  url: https://github.com/libarchive/libarchive/releases/download/v{{ version }}/libarchive-{{ version }}.tar.gz
  sha256: c676146577d989189940f1959d9e3980d28513d74eedfbc6b7f15ea45fe54ee2
  patches:
    - patches/0001-Add-lib-to-CMAKE_FIND_LIBRARY_PREFIXES-for-lzma.patch
    - patches/0003-VC9-compatibility-test-for-BCryptDeriveKeyPBKDF2.patch
    - patches/0004-VC9-compatibility-define-BCRYPT_SUCCESS.patch
    - patches/0006-VC-openssl-define-inline-as-__inline.patch
    # These warnings are errors when compiling lz-4 support
    - patches/0007-CMake-VC9-compatibility-ignore-some-warnings.patch
    - patches/0008-VC9-compatibility-remove-C99.patch
    - patches/0009-CMake-Force-Multi-threaded-DLL-runtime.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    # Does not work in this recipe at present
    # we manually convert C99 to C89 instead.
    # - c99-to-c89  # [win and vc<14]
    - msinttypes  # [win and vc<14]
    - autoconf    # [unix]
    - automake    # [unix]
    - libtool     # [unix]
    - pkg-config  # [unix]
    - cmake       # [win]
    - make        # [unix]
    # - ninja       # [win]
    - m2-patch  # [win]
    - m2-gcc-libs  # [win]
    - patch  # [not win]
    # Used by bld.bat as an in-build test
    # - curl        # [win]
  host:
    - msinttypes  # [win and vc<14]
    - bzip2
    - libiconv    # [osx]
    - zlib
    - zstd

test:
  commands:
    # Verify pkg-config file is in place.
    - test -f "${PREFIX}/lib/pkgconfig/libarchive.pc"  # [unix]

    # Verify headers are in place.
    - test -f "${PREFIX}/include/archive.h"            # [unix]
    - test -f "${PREFIX}/include/archive_entry.h"      # [unix]
    - if not exist %LIBRARY_INC%\\archive.h        exit 1     # [win]
    - if not exist %LIBRARY_INC%\\archive_entry.h  exit 1     # [win]

    # Verify libraries are in place.
    - test -f "${PREFIX}/lib/libarchive.a"             # [unix]
    - test -f "${PREFIX}/lib/libarchive_and_deps.a"    # [unix]
    - if not exist %LIBRARY_LIB%\archive_and_deps.lib  exit 1  # [win]
    - if not exist %LIBRARY_LIB%\archive_static.lib  exit 1    # [win]
    - if not exist %LIBRARY_LIB%\zstd_static.lib  exit 1       # [win]
    - if not exist %LIBRARY_LIB%\bzip2_static.lib  exit 1      # [win]
    - if not exist %LIBRARY_LIB%\zlibstatic.lib  exit 1        # [win]

about:
  home: https://libarchive.org/
  summary: a static build of libarchive containing only conda-related parts
  license: BSD-2-Clause
  license_family: BSD
  dev_url: https://github.com/libarchive/libarchive
  doc_url: https://github.com/libarchive/libarchive/wiki
  doc_source_url: https://github.com/libarchive/libarchive/tree/master/doc
  license_url: https://github.com/libarchive/libarchive/blob/master/COPYING
  license_file:
    - COPYING
    - static_deps_licenses/bzip2.txt
    - static_deps_licenses/libarchive.txt
    - static_deps_licenses/zlib.txt
    - static_deps_licenses/zstd.txt
    - static_deps_licenses/msinttypes.txt  # [win and py27]
    - static_deps_licenses/libiconv.txt    # [osx]
  description: |
    The libarchive project develops a portable, efficient 
    C library that can read and write streaming archives in a variety of formats. 
    It also includes implementations of the common tar, cpio, 
    and zcat command-line tools that use the libarchive library.

extra:
  recipe-maintainers:
    - mingwandroid
    - msarahan
    - jjhelmus
